/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.bkeryorsi.menyasszonyiruhakolcsonzo.felulet;

import hu.bkeryorsi.menyasszonyiruhakolcsonzo.SQL;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.adatbazis.Kolcsonzes;
import java.util.Date;

/**
 *
 * @author keryo
 */
public class KolcsonzesFelulet extends javax.swing.JPanel {

    /**
     * Creates new form KolcsonzesKezeles
     */
    private FoPanel szulo;

    public KolcsonzesFelulet(FoPanel szulo) {
        this.szulo = szulo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ruhakolcs_gomb = new javax.swing.JButton();
        fatyolkolcs_gomb = new javax.swing.JButton();
        kesztyukolcs_gomb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kereses_gomb = new javax.swing.JButton();
        emailCim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kolcsonzesek = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        visszavesz_gomb = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(890, 600));

        jLabel1.setText("Kölcsönzések kezelése");

        ruhakolcs_gomb.setText("Új ruha kölcsönzése");
        ruhakolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruhakolcs_gombActionPerformed(evt);
            }
        });

        fatyolkolcs_gomb.setText("Új fátyol kölcsönzése");
        fatyolkolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatyolkolcs_gombActionPerformed(evt);
            }
        });

        kesztyukolcs_gomb.setText("Új kesztyű kölcsönzése");
        kesztyukolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kesztyukolcs_gombActionPerformed(evt);
            }
        });

        jLabel2.setText("A visszavételhez adja meg az ügyfél e-mail címét:");

        kereses_gomb.setText("Keresés");
        kereses_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kereses_gombActionPerformed(evt);
            }
        });

        emailCim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCimActionPerformed(evt);
            }
        });

        jLabel3.setText("Az ügyfélnél kint lévő termékek:");

        kolcsonzesek.setColumns(20);
        kolcsonzesek.setRows(5);
        jScrollPane1.setViewportView(kolcsonzesek);

        jLabel4.setText("Figyelem! Visszavételkor az összes terméket vissza kell hozni.");

        visszavesz_gomb.setText("Az összeset visszavesz");
        visszavesz_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visszavesz_gombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(ruhakolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatyolkolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kesztyukolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(209, 209, 209))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailCim, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addComponent(kereses_gomb))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(visszavesz_gomb)
                        .addGap(322, 322, 322))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(220, 220, 220))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ruhakolcs_gomb)
                    .addComponent(emailCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(fatyolkolcs_gomb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(kereses_gomb)))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kesztyukolcs_gomb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(visszavesz_gomb)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ruhakolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruhakolcs_gombActionPerformed
        UjRuhaKolcsonzes ujRuhaKolcsonzes = new UjRuhaKolcsonzes(szulo);
        szulo.panelmutat(ujRuhaKolcsonzes);
    }//GEN-LAST:event_ruhakolcs_gombActionPerformed

    private void fatyolkolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatyolkolcs_gombActionPerformed
        UjFatyolKolcsonzes ujFatyolKolcsonzes = new UjFatyolKolcsonzes(szulo);
        szulo.panelmutat(ujFatyolKolcsonzes);
    }//GEN-LAST:event_fatyolkolcs_gombActionPerformed

    private void kesztyukolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kesztyukolcs_gombActionPerformed
        UjKesztyuKolcsonzes ujKesztyuKolcsonzes = new UjKesztyuKolcsonzes(szulo);
        szulo.panelmutat(ujKesztyuKolcsonzes);
    }//GEN-LAST:event_kesztyukolcs_gombActionPerformed

    private void kereses_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kereses_gombActionPerformed
        SQL sql = new SQL();
        int ugyfelid = sql.getugyfelId(emailCim.getText());

        kolcsonzesek.setText(Eszkozok.formaz(sql.getKolcsonzes(ugyfelid)));
    }//GEN-LAST:event_kereses_gombActionPerformed

    private void emailCimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCimActionPerformed

    private void visszavesz_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visszavesz_gombActionPerformed
        SQL sql = new SQL();
        int ugyfelid = sql.getugyfelId(emailCim.getText());
        Kolcsonzes k = sql.getKolcsonzes(ugyfelid);
        if (k.getMenyasszonyiRuhaId() != null) {
            sql.ruhaStatuszModositas(k.getMenyasszonyiRuhaId(), "tisztító");
            
        }
        if (k.getFatyolId() != null) {
            sql.fatyolStatuszModositas(k.getFatyolId(), "tisztító");
         

    }//GEN-LAST:event_visszavesz_gombActionPerformed
        if (k.getKesztyuId() != null) {
            sql.kesztyuStatuszModositas(k.getKesztyuId(), "tisztító");
         
        }
        sql.visszavetel(k.getKolcsonzesid());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailCim;
    private javax.swing.JButton fatyolkolcs_gomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kereses_gomb;
    private javax.swing.JButton kesztyukolcs_gomb;
    private javax.swing.JTextArea kolcsonzesek;
    private javax.swing.JButton ruhakolcs_gomb;
    private javax.swing.JButton visszavesz_gomb;
    // End of variables declaration//GEN-END:variables
}
