/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.bkeryorsi.menyasszonyiruhakolcsonzo.felulet;

/**
 *
 * @author keryo
 */
public class KolcsonzesFelulet extends javax.swing.JPanel {

    /**
     * Creates new form KolcsonzesKezeles
     */
    private FoPanel szulo;
    public KolcsonzesFelulet(FoPanel szulo) {
        this.szulo = szulo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ruhakolcs_gomb = new javax.swing.JButton();
        fatyolkolcs_gomb = new javax.swing.JButton();
        kesztyukolcs_gomb = new javax.swing.JButton();
        ruhavisszav_gomb = new javax.swing.JButton();
        fatyolvisszav_gomb = new javax.swing.JButton();
        kesztyuvisszav_gomb = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(890, 600));

        jLabel1.setText("Kölcsönzések kezelése");

        ruhakolcs_gomb.setText("Új ruha kölcsönzése");
        ruhakolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruhakolcs_gombActionPerformed(evt);
            }
        });

        fatyolkolcs_gomb.setText("Új fátyol kölcsönzése");
        fatyolkolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatyolkolcs_gombActionPerformed(evt);
            }
        });

        kesztyukolcs_gomb.setText("Új kesztyű kölcsönzése");
        kesztyukolcs_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kesztyukolcs_gombActionPerformed(evt);
            }
        });

        ruhavisszav_gomb.setText("Ruha visszavétel");

        fatyolvisszav_gomb.setText("Fátyol visszavétel");

        kesztyuvisszav_gomb.setText("Kesztyű visszavétel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(ruhakolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatyolkolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kesztyukolcs_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kesztyuvisszav_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ruhavisszav_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fatyolvisszav_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruhakolcs_gomb)
                    .addComponent(ruhavisszav_gomb))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fatyolkolcs_gomb)
                    .addComponent(fatyolvisszav_gomb))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kesztyukolcs_gomb)
                    .addComponent(kesztyuvisszav_gomb))
                .addContainerGap(283, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ruhakolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruhakolcs_gombActionPerformed
         UjRuhaKolcsonzes ujRuhaKolcsonzes = new UjRuhaKolcsonzes(szulo);
        szulo.panelmutat(ujRuhaKolcsonzes);
    }//GEN-LAST:event_ruhakolcs_gombActionPerformed

    private void fatyolkolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatyolkolcs_gombActionPerformed
        UjFatyolKolcsonzes ujFatyolKolcsonzes = new UjFatyolKolcsonzes(szulo);
        szulo.panelmutat(ujFatyolKolcsonzes);
    }//GEN-LAST:event_fatyolkolcs_gombActionPerformed

    private void kesztyukolcs_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kesztyukolcs_gombActionPerformed
      UjKesztyuKolcsonzes ujKesztyuKolcsonzes = new UjKesztyuKolcsonzes(szulo);
        szulo.panelmutat(ujKesztyuKolcsonzes);
    }//GEN-LAST:event_kesztyukolcs_gombActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fatyolkolcs_gomb;
    private javax.swing.JButton fatyolvisszav_gomb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kesztyukolcs_gomb;
    private javax.swing.JButton kesztyuvisszav_gomb;
    private javax.swing.JButton ruhakolcs_gomb;
    private javax.swing.JButton ruhavisszav_gomb;
    // End of variables declaration//GEN-END:variables
}
