/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.bkeryorsi.menyasszonyiruhakolcsonzo.felulet;

import hu.bkeryorsi.menyasszonyiruhakolcsonzo.SQL;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.adatbazis.Fatyol;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.adatbazis.Ruha;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.felulet.eszkozok.SzamFilter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.PlainDocument;

/**
 *
 * @author keryo
 */
public class Ruhaink extends javax.swing.JPanel {
private FoPanel szulo;
    /**
     * Creates new form Ruhaink
     */
    public Ruhaink(FoPanel szulo) {
        this.szulo=szulo;
        initComponents();
        PlainDocument doc = (PlainDocument) id.getDocument();
        doc.setDocumentFilter(new SzamFilter());
        PlainDocument doc2 = (PlainDocument) meret.getDocument();
        doc2.setDocumentFilter(new SzamFilter());
        SQL sql = new SQL();
        List<Ruha> ruha = sql.getRuha();
        ruhaBetolt(ruha);

    }

    private void ruhaBetolt(List<Ruha> ruha) {
        Object o[][] = new Object[ruha.size()][7];
        for (int i = 0; i < ruha.size(); i++) {
            Ruha k = new Ruha();
            k = ruha.get(i);

            o[i][0] = k.getId();
            o[i][1] = k.getLeiras();
            o[i][2] = k.getMeret();
            o[i][3] = k.getAr();
            o[i][4] = k.getFazon();
            o[i][5] = k.getAllapot();
            o[i][6] = k.getMegjegyzes();
        }

        String[] columnNames = {"Id", "Leírás","Méret", "Ár", "Fazon", "Állapot", "Megjegyzés"};
        Class[] columnClass = {Integer.class, String.class, String.class, Integer.class, String.class, String.class, String.class};
        DefaultTableModel model = new DefaultTableModel(o, columnNames) {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return columnClass[column];
            }
        };
        jTable1.setRowHeight(100);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fazonComboBox1 = new javax.swing.JComboBox<>();
        meret = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        allapotComboBox2 = new javax.swing.JComboBox<>();
        szures_gomb = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        uj_ruha_gomb = new javax.swing.JButton();
        ruha_megnyitasa_gomb = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(890, 600));

        jLabel1.setText("Ruháink");

        jLabel2.setText("Azonosító:");

        jLabel3.setText("Méret:");

        jLabel4.setText("Fazon:");

        fazonComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Sellő", "Félsellő", "Hercegnős" }));

        meret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meretActionPerformed(evt);
            }
        });

        jLabel5.setText("Állapot:");

        allapotComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Kölcsönözhető", "Kölcsönözve", "Tisztító", "Sérült" }));

        szures_gomb.setText("Szűrés");
        szures_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szures_gombActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        uj_ruha_gomb.setText("Új ruha felvétele");
        uj_ruha_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uj_ruha_gombActionPerformed(evt);
            }
        });

        ruha_megnyitasa_gomb.setText("Kijelölt ruha megnyitása");
        ruha_megnyitasa_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruha_megnyitasa_gombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id)
                            .addComponent(meret, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fazonComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uj_ruha_gomb))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ruha_megnyitasa_gomb, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(406, 406, 406))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(allapotComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(szures_gomb)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fazonComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(allapotComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(szures_gomb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(meret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uj_ruha_gomb)
                    .addComponent(ruha_megnyitasa_gomb))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void meretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meretActionPerformed

    private void szures_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szures_gombActionPerformed
    int beirtId;
        if (this.id.getText()!=null && !this.id.getText().equals("")){
        
    
         beirtId = (Integer.parseInt(this.id.getText()));
    } else {
            beirtId = 0;
            
            }
    int beirtMeret;
        if (this.meret.getText()!=null && !this.meret.getText().equals("")){
        
    
         beirtMeret = (Integer.parseInt(this.meret.getText()));
    } else {
            beirtMeret = 0;
            
            }
        
        String allapot = (String.valueOf(this.allapotComboBox2.getSelectedItem()));
        String fazon = (String.valueOf(this.fazonComboBox1.getSelectedItem()));
        
        SQL sql = new SQL();
        List<Ruha> ruha = sql.searchRuha(beirtId, fazon, allapot, beirtMeret);
        ruhaBetolt(ruha); 
    }//GEN-LAST:event_szures_gombActionPerformed

    private void uj_ruha_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uj_ruha_gombActionPerformed
     Ruhafelvetel ruhafelvetel = new Ruhafelvetel(szulo);
        szulo.panelmutat(ruhafelvetel); 
    }//GEN-LAST:event_uj_ruha_gombActionPerformed

    private void ruha_megnyitasa_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruha_megnyitasa_gombActionPerformed
    Ruha ruha = this.kivalasztottsor();
        Ruhamodositas ruhamodositas = new Ruhamodositas(szulo, ruha);
        szulo.panelmutat(ruhamodositas);
    }//GEN-LAST:event_ruha_megnyitasa_gombActionPerformed

    public Ruha kivalasztottsor() {
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        Ruha k = new Ruha();
        k.setId((Integer) model.getValueAt(i, 0));
        k.setLeiras((String)model.getValueAt(i, 1));
        k.setMeret((Integer) model.getValueAt(i, 2));
        k.setAr((Integer) model.getValueAt(i, 3));
        k.setFazon((String)model.getValueAt(i, 4));
        k.setAllapot((String) model.getValueAt(i, 5));
        k.setMegjegyzes((String) model.getValueAt(i, 6));
        return k;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> allapotComboBox2;
    private javax.swing.JComboBox<String> fazonComboBox1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField meret;
    private javax.swing.JButton ruha_megnyitasa_gomb;
    private javax.swing.JButton szures_gomb;
    private javax.swing.JButton uj_ruha_gomb;
    // End of variables declaration//GEN-END:variables
}
