/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hu.bkeryorsi.menyasszonyiruhakolcsonzo.felulet;

import hu.bkeryorsi.menyasszonyiruhakolcsonzo.SQL;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.adatbazis.Ruha;
import hu.bkeryorsi.menyasszonyiruhakolcsonzo.adatbazis.Ugyfel;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author keryo
 */
public class Ugyfelek extends javax.swing.JPanel {

    private FoPanel szulo;

    public Ugyfelek(FoPanel szulo) {
        this.szulo = szulo;
        initComponents();
        SQL sql = new SQL();
        List<Ugyfel> ugyfel = sql.getUgyfel();
        ugyfelBetolt(ugyfel);
    }

    private void ugyfelBetolt(List<Ugyfel> ugyfel) {
        Object o[][] = new Object[ugyfel.size()][4];
        for (int i = 0; i < ugyfel.size(); i++) {
            Ugyfel k = new Ugyfel();
            k = ugyfel.get(i);
            o[i][0] = k.getId();
            o[i][1] = k.getVezeteknev();
            o[i][2] = k.getKeresztnev();
            o[i][3] = k.getEmailcim();

        }

        String[] columnNames = {"Id", "Vezetéknév", "Keresztnév", "E-mail cím"};
        Class[] columnClass = {Integer.class, String.class, String.class, String.class};
        DefaultTableModel model = new DefaultTableModel(o, columnNames) {
            //  Returning the Class of each column will allow different
            //  renderers to be used based on Class
            @Override
            public Class getColumnClass(int column) {
                return columnClass[column];
            }
        };
        jTable1.setRowHeight(100);
        jTable1.setModel(model);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vezeteknev = new javax.swing.JTextField();
        vezeteknev_kereses_gomb = new javax.swing.JButton();
        ugyfel_megynyitas_gomb = new javax.swing.JButton();
        uj_ugyfel_gomb = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        keresztnev = new javax.swing.JTextField();
        keresztnev_kereses_gomb = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(890, 600));
        setRequestFocusEnabled(false);

        jLabel1.setText("Ügyfelek");

        jLabel2.setText("Ügyfél vezetékneve:");

        vezeteknev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezeteknevActionPerformed(evt);
            }
        });

        vezeteknev_kereses_gomb.setText("Keresés");
        vezeteknev_kereses_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezeteknev_kereses_gombActionPerformed(evt);
            }
        });

        ugyfel_megynyitas_gomb.setText("Kijelölt ügyfél megnyitása");
        ugyfel_megynyitas_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugyfel_megynyitas_gombActionPerformed(evt);
            }
        });

        uj_ugyfel_gomb.setText("Új ügyfél felvétele");
        uj_ugyfel_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uj_ugyfel_gombActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Ügyfél keresztneve:");

        keresztnev_kereses_gomb.setText("Keresés");
        keresztnev_kereses_gomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keresztnev_kereses_gombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ugyfel_megynyitas_gomb, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                    .addComponent(uj_ugyfel_gomb, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(42, 42, 42))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(43, 43, 43)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vezeteknev, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addComponent(keresztnev))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vezeteknev_kereses_gomb)
                                        .addComponent(keresztnev_kereses_gomb))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vezeteknev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vezeteknev_kereses_gomb))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(keresztnev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keresztnev_kereses_gomb))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ugyfel_megynyitas_gomb)
                    .addComponent(uj_ugyfel_gomb))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vezeteknev_kereses_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezeteknev_kereses_gombActionPerformed
        String vezeteknev = this.vezeteknev.getText();
        SQL sql = new SQL();
        List<Ugyfel> ugyfel = sql.searchUgyfelVezeteknev(vezeteknev);
        ugyfelBetolt(ugyfel);

    }//GEN-LAST:event_vezeteknev_kereses_gombActionPerformed

    private void uj_ugyfel_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uj_ugyfel_gombActionPerformed
        Ugyfelfelvetel ugyfelfelvetel = new Ugyfelfelvetel(szulo);
        szulo.panelmutat(ugyfelfelvetel);

    }//GEN-LAST:event_uj_ugyfel_gombActionPerformed

    private void ugyfel_megynyitas_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugyfel_megynyitas_gombActionPerformed
        Ugyfel ugyfel = this.kivalasztottsor();
        Ugyfelmodositas ugyfelmodositas = new Ugyfelmodositas(szulo, ugyfel);
        szulo.panelmutat(ugyfelmodositas);
    }

    public Ugyfel kivalasztottsor() {
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        Ugyfel k = new Ugyfel();
        k.setId((Integer) model.getValueAt(i, 0));
        k.setVezeteknev((String) model.getValueAt(i, 1));
        k.setKeresztnev((String) model.getValueAt(i, 2));
        k.setEmailcim((String) model.getValueAt(i, 3));
        return k;
    }//GEN-LAST:event_ugyfel_megynyitas_gombActionPerformed

    private void vezeteknevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezeteknevActionPerformed


    }//GEN-LAST:event_vezeteknevActionPerformed

    private void keresztnev_kereses_gombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keresztnev_kereses_gombActionPerformed
        String keresztnev = this.keresztnev.getText();
        SQL sql = new SQL();
        List<Ugyfel> ugyfel = sql.searchUgyfelKeresztnev(keresztnev);
        ugyfelBetolt(ugyfel);
    }//GEN-LAST:event_keresztnev_kereses_gombActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField keresztnev;
    private javax.swing.JButton keresztnev_kereses_gomb;
    private javax.swing.JButton ugyfel_megynyitas_gomb;
    private javax.swing.JButton uj_ugyfel_gomb;
    private javax.swing.JTextField vezeteknev;
    private javax.swing.JButton vezeteknev_kereses_gomb;
    // End of variables declaration//GEN-END:variables
}
